services:
  # バックエンド（FastAPI）
  - type: web
    name: visa-expert-backend
    env: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  # フロントエンド（React）
  - type: web
    name: visa-expert-frontend
    env: node
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://visa-expert-backend.onrender.com/api/*
